import { Routes } from '@angular/router';
import { HomeComponent } from './components/home/home.component';
import { LoginComponent } from './components/login/login.component';
import { RegisterComponent } from './components/register/register.component';
import { AdminDashboardComponent } from './components/admin-dashboard/admin-dashboard.component';
import { DashboardComponent } from './components/dashboard/dashboard.component';
import { ProfileComponent } from './components/profile/profile.component';
import { AddToCartComponent } from './components/add-to-cart/add-to-cart.component';
import { PaymentComponent } from './components/payment/payment.component';
import { HistoryComponent } from './components/history/history.component';
import { TrackOrderComponent } from './components/track-order/track-order.component';
import { ForgotPasswordComponent } from './components/forgot-password/forgot-password.component';
import { CustomCakeBuilderComponent } from './components/custom-cake-builder/custom-cake-builder.component';

export const routes: Routes = [
  { path: '', component: HomeComponent },
  { path: 'login', component: LoginComponent },
  { path: 'register', component: RegisterComponent },
  { path: 'admin-dashboard', component: AdminDashboardComponent },
  { path: 'dashboard', component: DashboardComponent },
  { path: 'profile', component: ProfileComponent },
  { path: 'payment', component: PaymentComponent },
  { path: 'add-to-cart', component: AddToCartComponent },
  { path: 'track-order', component: TrackOrderComponent },
  { path: 'forgot-password', component: ForgotPasswordComponent },
  { path: 'history', component: HistoryComponent },
  { path: 'custom-cake', component: CustomCakeBuilderComponent },
  { path: '**', redirectTo: '' }
];